import localFont from "next/font/local";
import "./globals.css";
import { Amplify } from 'aws-amplify';
import awsmobile from '../aws-exports.js'; // e.g., '../amplify-config.json' or '../src/aws-exports.js'

// Configure Amplify once at the top level
Amplify.configure(awsmobile);


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
